from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(557, 265)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelSourceFileIntro = QtWidgets.QLabel(self.centralwidget)
        self.LabelSourceFileIntro.setGeometry(QtCore.QRect(150, 10, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelSourceFileIntro.setFont(font)
        self.LabelSourceFileIntro.setObjectName("LabelSourceFileIntro")
        self.TextEditFileSourcePath = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditFileSourcePath.setGeometry(QtCore.QRect(70, 40, 471, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditFileSourcePath.setFont(font)
        self.TextEditFileSourcePath.setObjectName("TextEditFileSourcePath")
        self.ToolButtonSetFileSourcePath = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButtonSetFileSourcePath.setGeometry(QtCore.QRect(10, 40, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ToolButtonSetFileSourcePath.setFont(font)
        self.ToolButtonSetFileSourcePath.setObjectName("ToolButtonSetFileSourcePath")
        self.ToolButtonSetDirectoryResultPath = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButtonSetDirectoryResultPath.setEnabled(True)
        self.ToolButtonSetDirectoryResultPath.setGeometry(QtCore.QRect(10, 110, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ToolButtonSetDirectoryResultPath.setFont(font)
        self.ToolButtonSetDirectoryResultPath.setObjectName("ToolButtonSetDirectoryResultPath")
        self.TextEditFileResultPath = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditFileResultPath.setEnabled(True)
        self.TextEditFileResultPath.setGeometry(QtCore.QRect(70, 110, 471, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditFileResultPath.setFont(font)
        self.TextEditFileResultPath.setObjectName("TextEditFileResultPath")
        self.LabelResultFileIntro = QtWidgets.QLabel(self.centralwidget)
        self.LabelResultFileIntro.setEnabled(True)
        self.LabelResultFileIntro.setGeometry(QtCore.QRect(150, 80, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelResultFileIntro.setFont(font)
        self.LabelResultFileIntro.setObjectName("LabelResultFileIntro")
        self.RadioButtonEncodeType = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonEncodeType.setEnabled(True)
        self.RadioButtonEncodeType.setGeometry(QtCore.QRect(10, 160, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RadioButtonEncodeType.setFont(font)
        self.RadioButtonEncodeType.setObjectName("RadioButtonEncodeType")
        self.RadioButtonDecodeType = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonDecodeType.setEnabled(True)
        self.RadioButtonDecodeType.setGeometry(QtCore.QRect(10, 190, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RadioButtonDecodeType.setFont(font)
        self.RadioButtonDecodeType.setObjectName("RadioButtonDecodeType")
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setGeometry(QtCore.QRect(140, 170, 401, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProgressBar.setFont(font)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setInvertedAppearance(False)
        self.ProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBar.setObjectName("ProgressBar")
        self.PushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonStart.setEnabled(False)
        self.PushButtonStart.setGeometry(QtCore.QRect(220, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PushButtonStart.setFont(font)
        self.PushButtonStart.setObjectName("PushButtonStart")
        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Кодек файлов"))
        self.LabelSourceFileIntro.setText(_translate("Window", "Выберите/введите путь файла обработки"))
        self.ToolButtonSetFileSourcePath.setText(_translate("Window", "..."))
        self.ToolButtonSetDirectoryResultPath.setText(_translate("Window", "..."))
        self.LabelResultFileIntro.setText(_translate("Window", "Выберите/введите путь файла назначения"))
        self.RadioButtonEncodeType.setText(_translate("Window", "кодировать"))
        self.RadioButtonDecodeType.setText(_translate("Window", "декодировать"))
        self.PushButtonStart.setText(_translate("Window", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
